- name: Crear tarea programada en el Programador de tareas de Windows
  hosts: mis_hosts
  tasks:
    - name: Crear tarea programada
      community.windows.win_scheduled_task:
        name: "Ejecutar Resilio Sync"
        description: "Tarea programada para ejecutar Resilio Sync"
        actions:
          - path: "PowerShell.exe"
            arguments: "-Command 'Start-Process -FilePath \"C:\\Users\\FERNANDO\\AppData\\Roaming\\Resilio Sync\\Resilio Sync.exe\"'"
        trigger:
          - daily:
              at: "03:00"