---
- name: Programar la ejecución de Resilio Sync en Windows
  hosts: mis_hosts
  tasks:
    - name: Crear tarea programada para ejecutar Resilio Sync
      win_scheduled_task:
        name: "Resilio Sync abrir2"
        description: "Ejecutar Resilio Sync a las 10:00 AM todos los días"
        executable: "C:\\Users\\FERNANDO\\AppData\\Roaming\\Resilio Sync\\Resilio Sync.exe"
        arguments: ""
        state: present
        enabled: yes
        run_level: highest
        start_time: "10:00"
        frequency: daily
        days_of_week: "*"