- name: Crear tarea programada para abrir una aplicación
  hosts: mis_hosts
  tasks:
    - name: Crear tarea programada
      win_scheduled_task:
        name: Resilio Sync abrir2
        description: Tarea programada para abrir una aplicación
        state: present
        enabled: yes
        hidden: no
        triggers:
          - type: boot
            enabled: yes
        actions:
          - path: "C:\\Users\\FERNANDO\\AppData\\Roaming\\Resilio Sync\\Resilio Sync.exe"
            arguments: ""
            working_directory: "C:\\Users\\FERNANDO\\AppData\\Roaming\\Resilio Sync\\Resilio Sync.exe"