- name: Crear tarea programada en el Programador de tareas de Windows
  hosts: mis_hosts
  tasks:
    - name: Crear tarea programada
      community.windows.win_scheduled_task:
        name: "Ejecutar MiScript"
        description: "Tarea programada para ejecutar mi script PowerShell"
        actions:
          - path: "PowerShell.exe"
            arguments: "-File 'C:\\Users\\FERNANDO\\Desktop\\Scripts\\ejecutar_aplicacion1.ps1'"
        trigger:
          - daily:
              at: "03:00"