- name: Eliminar tarea programada existente
  hosts: mis_hosts
  tasks:
    - name: Eliminar tarea programada si existe
      win_scheduled_task:
        name: Resilio Sync abrir2
        state: absent